resilience4j:
  circuitbreaker:
    instances:
      avaliacaoCB:
        minimumNumberOfCalls: 4
        slidingWindowSize: 8

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include:
          - 'health'
          - 'prometheus'
  endpoint:
    health:
      enabled: true
      show-details: always
    prometheus:
      enabled: true

apiavaliacoes:
  url: 'http://${API_AVALIACOES_NAME}:${API_AVALIACOES_PORT}/avaliacoes'
